version: "3.8"

services:
  server:
    container_name: springboot-rest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      springboot-postgres-net:
    restart: on-failure
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      springboot-postgres-net:

  redis:
      container_name: redis
      image: redis
      ports:
        - "6379:6379"
      networks:
        - springboot-postgres-net

  maildev:
    container_name: maildev
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - springboot-postgres-net


networks:
  springboot-postgres-net: